In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [3]:
df = pd.read_csv("car data.csv")

In [4]:
df.head()

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0

In [5]:
df.shape

(301, 9)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Car_Name       301 non-null    str
 1   Year           301 non-null    int64
 2   Selling_Price  301 non-null    float64
 3   Present_Price  301 non-null    float64
 4   Kms_Driven     301 non-null    int64
 5   Fuel_Type      301 non-null    str
 6   Seller_Type    301 non-null    str
 7   Transmission   301 non-null    str
 8   Owner          301 non-null    int64
dtypes: float64(2), int64(3), str(4)
memory usage: 21.3 KB

In [7]:
df.isnull().sum()

Car_Name         0
Year             0
Selling_Price    0
Present_Price    0
Kms_Driven       0
Fuel_Type        0
Seller_Type      0
Transmission     0
Owner            0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(2)

In [9]:
y = df["Selling_Price"]

In [10]:
X = df.drop("Selling_Price", axis=1)

In [11]:
X = pd.get_dummies(X, drop_first=True)

In [12]:
X.head()

,Year,Present_Price,Kms_Driven,Owner,Car_Name_Activa 3g,Car_Name_Activa 4g,Car_Name_Bajaj ct 100,Car_Name_Bajaj Avenger 150,Car_Name_Bajaj Avenger 150 street,Car_Name_Bajaj Avenger 220,...,Car_Name_swift,Car_Name_sx4,Car_Name_verna,Car_Name_vitara brezza,Car_Name_wagon r,Car_Name_xcent,Fuel_Type_Diesel,Fuel_Type_Petrol,Seller_Type_Individual,Transmission_Manual
0,2014,5.59,27000,0,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,True
1,2013,9.54,43000,0,False,False,False,False,False,False,...,False,True,False,False,False,False,True,False,False,True
2,2017,9.85,6900,0,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,True
3,2011,4.15,5200,0,False,False,False,False,False,False,...,False,False,False,False,True,False,False,True,False,True
4,2014,6.87,42450,0,False,False,False,False,False,False,...,True,False,False,False,False,False,True,False,False,True

In [13]:
X.shape

(301, 105)

In [14]:
X_train, X_test, y_train, y_test = train_test_split( X,y,test_size=0.2,random_state=42)

In [15]:
rf_model = RandomForestRegressor(n_estimators=100,random_state=42)

In [16]:
rf_model.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [17]:
y_pred = rf_model.predict(X_test)

In [18]:
print(y_pred[:10])

[ 0.429  10.3568  4.969   0.2084  7.4118  6.598   1.122   0.5887  0.4619
  6.7705]

In [19]:
comparison = pd.DataFrame({"Actual Price": y_test.values,"Predicted Price": y_pred})
comparison.head(10)

   Actual Price  Predicted Price
0          0.35           0.4290
1         10.11          10.3568
2          4.95           4.9690
3          0.15           0.2084
4          6.95           7.4118
5          7.45           6.5980
6          1.10           1.1220
7          0.50           0.5887
8          0.45           0.4619
9          6.00           6.7705

In [20]:
mae = mean_absolute_error(y_test, y_pred)
print("Mean Absolute Error:", mae)

Mean Absolute Error: 0.5811213114754101

In [21]:
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

Mean Squared Error: 0.7371188062295083

In [22]:
r2 = r2_score(y_test, y_pred)
print("R² Score:", r2)

R² Score: 0.9680008638122364